// <auto-generated />
using Calculator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Calculator.Migrations
{
    [DbContext(typeof(CalculatorContext))]
    partial class CalculatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Calculator.Models.Formula", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("Const1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Const2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Const3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Const4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Const5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("GenderID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GenderID");

                    b.ToTable("Formulas");
                });

            modelBuilder.Entity("Calculator.Models.Gender", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Genders");
                });

            modelBuilder.Entity("Calculator.Models.Formula", b =>
                {
                    b.HasOne("Calculator.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");
                });
#pragma warning restore 612, 618
        }
    }
}
